### ISSUE TITLE
Add isinstance behavior

### ISSUE THREAD

**Issue by NeilGirdhar** [CarliJoy/intersection_examples#10]
This should probably work and do the obvious thing:
```python
if isinstance(x, A & B)
```
since it works for unions.

**Comment by randolf-scholz** [comment]
As special cases, it might be worth adding what happens with empty intersections / unions:


- empty `Union` must alias to `Never`, hence testing empty `Union` must always return `False`
   - [x] `isinstance(x, ())` currently always returns `False` 
   - [ ] `isinstance(x, Union)` currently unsupported
   - [ ] `Union[()]` currently unsupported
- empty `Intersection` must alias to `Any`, hence testing empty `Intersection` must always return `True`
   - if simplification is implemented (https://github.com/CarliJoy/intersection_examples/issues/5) then 

I suggest rethinking to allow `Union` and `Intersection` to accept no arguments, and return the appropriate `Never` or `Any`. (or `Union[Never]` and `Intersection[Any]`): https://github.com/python/typing/issues/1362

**Comment by NeilGirdhar** [comment]
`Union[]` is already discussed in a different thread.  Since `Union` is deprecated, it's simply going to go away on its own.  There's no need to bring it up in this PEP.

Similarly, empty intersection doesn't need to work or be mentioned in my opinion.  When `Intersection` disappears in a few Python versions, you won't be able to write an empty intersection.

**Comment by randolf-scholz** [comment]
@NeilGirdhar The same reasoning as in https://github.com/CarliJoy/intersection_examples/issues/12#issuecomment-1657069873 applies as to why the actual types `Union` and `Intersection` can't disappear.

**Comment by NeilGirdhar** [comment]
I guess if you want this, you should convince people in this thread: https://github.com/python/typing/issues/1362?  Anyway, I think this should have been a separate issue.

**Comment by mikeshardmind** [comment]
@randolf-scholz 
> empty Intersection must alias to Any

I believe that this should alias to `object` and don't really want to rehash all the stuff from #1

Can we agree on this simply, or should we wait to see a resolution on #1 ?

Note: The reason An empty Union is Never is the same reason why Never is removable from a Union with other types

**Comment by randolf-scholz** [comment]
Yes, it should have been object.

**Comment by kmillikin** [comment]
> Note: The reason An empty Union is Never is the same reason why Never is removable from a Union with other types

This is right.  It's also a consequence of a property of subtypes of union types.  A type is a subtype of a union type if it is a subtype of at least one component of the union.  Trivially, there is *no* type that is a subtype of at least one component of an empty union type.  Therefore, an empty union type is a type that has no subtypes.

Dually for intersections (though it might seem a bit weird): a type is a subtype of an intersection type if it is a subtype of all the components of the intersection.  Trivially, every type is a subtype of all the (none) components of an empty intersection type.  Therefore, an empty intersection type is a type that is a supertype of every type.

But note that this is not necessarily `object`.  There can be more than one top type.

**Comment by kmillikin** [comment]
My opinion is that raw `Intersection` is nonsense.  If `Intersection` were a generic type, then this would be implicitly instantiated somehow (`Intersection[Any]`?).

But `Intersection` is not a generic type, it's just some special form and there's no reason that raw `Intersection` has to mean anything at all (except a static error).

We would thus avoid the confusion between programmers who expect that `Intersection` is a top type wrt. subtyping and programmers who think it's like a raw generic and it's `Intersection[Any]`.  We avoid saying whether it is a distinct type from `object` or not.  We don't need it, because we already have `object`.

**Comment by randolf-scholz** [comment]
@kmillikin Here's an example for empty intersection:

```python
from typing import TypeVarTuple, Intersection

protocols = TypeVarTuple("protocols")
# note: bounds currently not supported, but what is meant is
# TypeVarTuple("protocols", bound=type[Protocol])

def create_intersection_protocol(protos: tuple[*protocols]) -> Intersection[*protocols]]: ...
    """Synthesizes the intersection-class of pairwise disjoint protocol classes."""
    # if intersection is empty, returns a protocol that matches with any class.

EMPTY_TUPLE = ()
create_intersection_protocol(EMPTY_TUPLE)  # what is the type?
```

I think the revealed type should be either `object`, or the unique empty `Protocol` "`Top`" from my last comment.

**Comment by kmillikin** [comment]
@randolf-scholz I don't understand your example at all, but I think it's irrelevant to the question of what raw `Intersection` is, since it doesn't use raw `Intersection`.

**Comment by kmillikin** [comment]
It's an interesting observation that protocols allow arbitrarily many distinct user-defined top types.  That's probably a bit of a mess for Python, but I think an intersection PEP can be silent on these.

**Comment by randolf-scholz** [comment]
@kmillikin The function `create_intersection_protocol` should synthesize the intersection of disjoint protocol classes. For example
`merge_protocol(Hashble, Sized)` should return a Protocol like

```Python
class HashableAndSized(Protocol):
    def __len__(self): ...
    def __hash_(self): ...
```

Which is essentially equivalent to `Hashable & Sized`.

**Comment by kmillikin** [comment]
Still seems irrelevant.

**Comment by randolf-scholz** [comment]
I think the question is simply whether bare `Union` and `Intersection` should be considered equivalent to `Union[()]` and `Intersection[()]`. (as a shorthand, since these look quite awkward)

I know that `Union[()]` currently raises an error, but imo it shouldn't. In the example I gave, the question is what is `reveal_type(merge_protocols(()))`? It should be `Intersection[()]` without simplification, and `object` or the suggested `typing.Top` empty-`Protocol` class with simplification. A similar example for `Union` can be made that shows how `Union[()]` can pop up naturally.

**Comment by NeilGirdhar** [comment]
Can we have this discussion in https://github.com/CarliJoy/intersection_examples/issues/20 where other people can find it?
