### ISSUE TITLE
The PEP should use & exclusively

### ISSUE THREAD

**Issue by NeilGirdhar** [CarliJoy/intersection_examples#12]
The PEP is inconsistent and uses `Intersection` sometimes.  It would be better to exclusively use the `&` notation, and mention the `Intersection` as existing solely in `typing_extensions` for backwards compatibility.

**Comment by randolf-scholz** [comment]
Intersection only existing in `typing_extensions` would be confusing, since `Union` does exist in `typing`. Also, for certain special applications, one might need to have the type available. For example, imagine someone writing a script for automatically adding annotations to code. How are they supposed to type-hint a function that detects `Intersections` and returns the annotation if the `Intersection`-type is not available?

**Comment by NeilGirdhar** [comment]
> . How are they supposed to type-hint a function that detects `Intersections` and returns the annotation, if the `Intersection`-type is not available?

Okay, good point.

Still, we should avoid `Intersection` completely I think.  There's no good reason to encourage anyone to use that.

**Comment by randolf-scholz** [comment]
I just want to mention one more example here, which requires `Union` and `Intersection`, which is when the number of things intersected is variable. This can happen when `TypeVarTuple` are involved, and it kind of implies that a speccing of empty unions and empty intersections is necessary. (See https://github.com/python/typing/issues/1362)


```python
from typing import TypeVarTuple, Union

items = TypeVarTuple("items")
protocols = TypeVarTuple("protocols")   # something like tuple[type[Protocol], ...]
# NOTE: https://peps.python.org/pep-0646/#variance-type-constraints-and-type-bounds-not-yet-supported

def pick_random_element(tup: tuple[*items]) -> Union[*items]: ...
    """Return random element form a tuple."""
    # if tuple is empty, raises an exception ⟺ return `Never`.

def create_intersection_protocol(tuple: tuple[*protocols]) -> type[Intersection[*Protocols]]: ...
    """Creates the intersection of pairwise disjoint protocol classes."""
    # if intersection is empty, returns a protocol that matches with any class.

EMPTY_TUPLE = ()
pick_random_element(EMPTY_TUPLE)  # should reveal as `Never`.
create_intersection_protocol(EMPTY_TUPLE)  # should reveal as `object`!?
````

**Comment by NeilGirdhar** [comment]
@randolf-scholz Could you please create a separate issue for that and then link it in #19?

**Comment by NeilGirdhar** [comment]
@randolf-scholz Okay, I thought about it, and I see what you're getting at.
