### ISSUE TITLE
Mention order of operations

### ISSUE THREAD

**Issue by NeilGirdhar** [CarliJoy/intersection_examples#18]
_And_ has higher precedence than _or_, so _intersection_ should have higher precedence than _union_.

**Comment by kmillikin** [comment]
That's conveniently what we get from `&` and `|`.

**Comment by NeilGirdhar** [comment]
True.  Should we mention it in the PEP or is it obvious enough?

**Comment by kmillikin** [comment]
I think it's worth mentioning that it's a consequence of Python's operator precedence.  No reason to leave a doubt about the PEP author's intention.
