### ISSUE TITLE
Handling collections -> mixin invariant and covariant types

### ISSUE THREAD

**Issue by CarliJoy** [CarliJoy/intersection_examples#2]
What happens if user mixes and invariant and covriant types?

i.e. 

`list[int] & Sequence[int]`

Will the result be a list that has an covariant int?

**Comment by erictraut** [comment]
> What happens if user mixes and invariant and covriant types?

In the interest of being precise, it's important to note that _types_ do not have variance; _type parameters_` have variance. For example, the `Mapping` class has two type parameters. The first is invariant and the second is covariant.

> Will the result be a list that has an covariant int?

I think the type `list[int] & Sequence[int]` is the equivalent of `list[int]`. That falls out of the generalized rule that `C` is a subtype of `A & B` if `C` is a subtype of `A` _and_ a subtype of `B`.

Similarly, `list[int] | Sequence[int]` is the equivalent of `Sequence[int]`. That falls out of the generalized rule that `C` is a subtype of `A | B` if `C` is the subtype of `A` _or_ a subtype of `B`.

**Comment by CarliJoy** [comment]
Thanks for the clarification.
So what happens if we do

```
Mapping[str, str] & Mapping[int, int]
```
?

**Comment by erictraut** [comment]
When thinking about unions and intersections, it's important to think in terms of set theory. The type annotation `Mapping[str, str]` describes a set of types — namely the type `Mapping[str, str]` and all subtypes thereof.

From a type theory standpoint, when you intersect the set of types described by `Mapping[str, str]` and the set of types described by `Mapping[int, int]`, you get a null set of types. The only types that would be compatible with it are `Never` or `Any`. 

This falls out of the rules that I proposed in the other thread for subtyping and attribute access.

**Comment by randolf-scholz** [comment]
@erictraut regarding preciseness, shouldn't the result be `Mapping[Never, Never]`? This is different from `Never`, because `Never` is uninhabited, i.e. has no instances, but for example an empty dictionary is technically an instance of `Mapping[Never, Never]`.

**Comment by erictraut** [comment]
> shouldn't the result [of `Mapping[str, str] & Mapping[int, int]`] be `Mapping[Never, Never]`.

I don't think so. `Mapping[Never, Never]` is not a subtype of `Mapping[str, str]` or `Mapping[int, int]` because the first type parameter to `Mapping` is invariant. That means `Mapping[Never, Never]` is not part of either of the sets, so it wouldn't be part of the intersection of the sets either. This is why it's important to think of this from a set theory standpoint.

If the intersection of `Mapping[str, str]` and `Mapping[int, int]` were `Mapping[Never, Never]`, then I would expect that the _union_ of the two would be `Mapping[object, object]`, but that's clearly not the case.

**Comment by randolf-scholz** [comment]
Right, my bad. But e.g. `Sequence[int] & Sequence[str]` should be `Sequence[Never]` instead of `Never` then.

**Comment by erictraut** [comment]
I agree that `Sequence[Never]` is a subtype of `Sequence[int] & Sequence[str]`, but I don't think they're equivalent sets — i.e. they're not equal. `Sequence[int & str]` is also a subtype of `Sequence[int] & Sequence[str]`, at least from a type theory standpoint. (I recognize that a value of type `int & str` cannot be realized at runtime, but this is an anomaly imposed by Python's runtime implementation, not dictated by type theory. If you replace `int` and `str` with two other classes like `Foo` and `Bar`, that limitation would disappear.)

**Comment by diabolo-dan** [comment]
I had naively expected that:

```
Mapping[int, int] & Mapping[str, str] ==		Mapping[int | str, int & str]
```
and
```
Mapping[int, int] | Mapping[str, str] == Mapping[int & str, int | str]
```

But the `Key` type argument to `Mapping` is of course invariant, not contravariant, because it appears in return types as well.

You can imagine some general rules based on variance like:
```
A[+T] =>
    A[x] & A[y] == A[x&y]
    A[x] | A[y] == A[x|y]
A[-T] =>
    A[x] & A[y] == A[x|y]
    A[x] | A[y] == A[x&y]
```
(`A[+T]`, `A[-T]` meaning covariant, contravariant in T respectively)

But `Sequence[x] | Sequence[y]` is more restrictive than `Sequence[x | y]` which makes me concerned that there might be other combinations that are invalid in one direction of the other.

**Comment by erictraut** [comment]
In general, intersections and unions are not reducible like this, so the rules you've listed above don't hold. There are some specific cases where they are reducible:

```
A[+T] =>
    A[x] & A[y] == A[x] if x <: y
    A[x] | A[y] == A[x] if y <: x
A[-T] =>
    A[x] & A[y] == A[x] if y <: x
    A[x] | A[y] == A[x] if x <: y
A[T] =>
    A[x] & A[y] == A[x] if x == y
    A[x] | A[y] == A[x] if x == y
```

**Comment by randolf-scholz** [comment]
@diabolo-dan @erictraut So, more generally, we should have

```
A[+T] =>
    A[x&y] ≤ A[x] & A[y]  (with equality if and only if x≤y or y≤x)
    A[x|y] ≥ A[x] | A[y]  (with equality if and only if x≤y or y≤x)
A[-T] =>
    A[x&y] ≥ A[x] & A[y]  (with equality if and only if  x≤y or y≤x)
    A[x|y] ≤ A[x] | A[y]  (with equality if and only if  x≤y or y≤x)
A[T] =>
    A[x&y] ≶ A[x] & A[y]  (incomparable with equality iff  x≤y or y≤x)
    A[x|y] ≶ A[x] | A[y]  (incomparable with equality iff  x≤y or y≤x)
```

right?

**Comment by erictraut** [comment]
That looks correct to me except for the "incomparable unless..." statements. I think those should read "equality if and only if x=y". (Or you could replace "or" with "and", since `x≤y and y≤x` implies `x=y`.)
