### ISSUE TITLE
Combination with `Self`

### ISSUE THREAD

**Issue by junkmd** [CarliJoy/intersection_examples#23]
While reading `specification.rst`, I had a question that crossed my mind.

In below case, unless `from __future__ import annotations` is used, a `NameError` is raised at runtime.

https://github.com/CarliJoy/intersection_examples/blob/bcca49112164a9a8b0cdfb94569bb379c734b722/specification.rst?plain=1#L89-L98

To avoid runtime errors, it's necessary to use string literals for typing as shown below.

```py
    class LoginRequiredMixin: 
        def dispatch(self: "LoginRequiredMixin & View", request, *args, **kwargs): ... 
```

For expressing that `self` is a mixin, in order to convey the same meaning without using string literals, I think that it should be typed with using [`Self`](https://docs.python.org/3/library/typing.html#typing.Self).

```py
    class LoginRequiredMixin: 
        def dispatch(self: Self & View, request, *args, **kwargs): ... 
```

Moreover, it's necessary to consider the interaction with methods and attributes that return `Self`.

```py
class Mixin:
    me: Self
 
 
a: Mixin & T
…
b = a.me
```

In the above case, I think that `b` should be interpreted as `Mixin & T` by type checkers.

Any opinions would be appreciated.

**Comment by CarliJoy** [comment]
Feel free to create an MR

**Comment by junkmd** [comment]
@CarliJoy

Hello!

I see, I will start working for the first pull request in this repo.

**Comment by junkmd** [comment]
#24 is merged.
