### ISSUE TITLE
Naming 4 vs 5

### ISSUE THREAD

**Issue by mark-todd** [CarliJoy/intersection_examples#36]
Starting this thread after discussion on https://github.com/CarliJoy/intersection_examples/issues/31 about what Option 4 and 5 should be renamed to.

Rules of this thread as follows - post simply the name suggestion in the style:

Option 4 -> *name*
Option 5 -> *name*

Most thumbs up in a few days wins!

I'll post up any already suggested names to get the ball rolling

**Comment by mark-todd** [comment]
Option 4 -> Any & T; Prioritise Any
Option 5 -> Any & T; Prioritise T

**Comment by mark-todd** [comment]
Option 4 -> Project Crossroad
Option 5 -> Project Junction

**Comment by DiscordLiz** [comment]
I think it's a bit premature to do this.
