### ISSUE TITLE
Organising the naming poll for `OrderedIntersection`

### ISSUE THREAD

**Issue by mark-todd** [CarliJoy/intersection_examples#44]
Just adding a new thread for this, as it occurred to me that when the PEP is ready we'll need to figure out how we organise the naming poll on python discuss that was mentioned before. I think we'll need to narrow down the list of available names before it goes to a poll, as right now we have many many possibles. I think perhaps each of us should eventually submit one name each that's our favourite, and we put these in a poll (as that should reduce it to 6 options or so).

Also here's the names list as it is currently - feel free to add to it: https://docs.google.com/spreadsheets/d/1rJlt5UfSOkVey2g5p634mKa0NdsCdpuZDwDfs4CnsiY/edit?usp=sharing

I've also been thinking some more about the points I've been discussing with @mikeshardmind, and this led me to some new thoughts about names. We established in our discussions that really `OrderedIntersection` is a combination of structural types, that aren't necessarily classes that can be combined together via inheritance, but are sort of structures layered on top of one another to produce a final result.

This led me to another "family" of names, where the idea is that it's kind of like a stack of differently shaped papers layered on top of each other (in art I've found this is called "paper layering"). I'm thinking a name of this type would describe quite accurately how objects are combined overlapping each other in a stack, and maybe avoid the parallel to inheritance that doesn't always apply.

Some names:

* **Overlap** - this one was suggested before, but I now think maybe has more merit than I initially thought, as it describes how classes overlap one another.

* **Stack** - again conveys this idea of ordered layering although maybe has too many parallels to heap and stack

* **Layered** - similar to stack

* **Bundle** - perhaps not ordered enough as a name

Looking for synonyms for `Stack` also led me to `Heap` and `Pile`, but again is this perhaps too much overlap with existing programming terms.

**Comment by DiscordLiz** [comment]
What's the reason to use another name?

Keeping "intersection" in the name helps this be obvious to those who already know what an intersection is or who were told they need to wait for python to have intersections to type something correctly.

**Comment by mikeshardmind** [comment]
In working on the draft, and some initial feedback I've gotten, I'm currently naming it as `Intersection` despite the reasons to **name** it `OrderedIntersection`, as well as including behavior for `&` all of it's justified in the [draft](https://gist.github.com/mikeshardmind/990a05a9673ca18238affa19dcc5cd8b) which I'll be converting to a PR later.

but it comes down to the fact that even though we can forsee a potential unordered form, the conditions for it might require a python 4.x or be narrow enough where places that `&` is allowed, it is always correct.

This is a case where the ergonomics should be good enough that people don't shy away from using it.

**Comment by mikeshardmind** [comment]
Draft has been moved over to #46, I'm putting a 📌 in this issue for now given the direction I took on the intitial feedback mentioned above. Revisiting this is possible if we reach a conclusion that the direction shift was misguided.
