### ISSUE TITLE
Generic type alias

### ISSUE THREAD

**Issue by junkmd** [CarliJoy/intersection_examples#7]
The efforts of everyone involved in this project are remarkable.

I am curious whether `Intersection` is intended to allow generic type aliases like `Union`. I noticed that [`TypeVar` is used in `specification.rst`](https://github.com/CarliJoy/intersection_examples/blob/667e425949be12849a08f6c094cbb0f867238d09/specification.rst?plain=1#L116-L132), which may imply that generic aliases are possible. 

If generic type aliases are possible, I think the specification would look like this:

```py
class Foo: ...
class Bar: ...
class FooBar(Foo, Bar): ...

_T = TypeVar("_T")

# cases of Union...
# pre-PEP604
Spam = Union[_T, Foo]
# post-PEP604, pre-PEP695
Spam = _T | Foo
# post-PEP695
type Spam[T] = T | Foo
# simple usecases
def bacon(spam: Spam[Bar]): ...
bacon(FooBar())  # OK
bacon(Foo())  # OK
bacon(Bar())  # OK
bacon(1)  # NG


# cases of Intersection...
# pre-PEP695
Ham = Intersection[_T, Foo]
Ham = _T & Foo
# post-PEP695
type Ham[T] = T & Foo
# simple usecases
def lettuce(ham: Ham[Bar]): ...
lettuce(FooBar())  # OK
lettuce(Foo())  # NG
lettuce(Bar())  # NG
lettuce(0)  # NG
```

Any opinions would be appreciated.

**Comment by tomasr8** [comment]
The examples look good to me, can't think of a reason to not allow that. Do you have an example where this could cause issues?

**Comment by junkmd** [comment]
No, there should be no issues. I believe these examples adhere to the existing rules of generic types, and they do not deviate from them.

I am confident that using generic `Intersection` type aliases as annotations for arguments, return values, and variables should not cause any problems.

On the other hand, there are already some generic type aliases that allow subtyping and calling, like the following:
```py
>>> Egg = list[_T | Foo] 
>>> Egg[Bar] 
list[typing.Union[__main__.Bar, __main__.Foo]]
>>> class BoiledEgg(Egg[_T]): ...
... 
>>> class BoiledEgg(Egg[_T]): ... 
...
>>> Egg()
[]
>>> BoiledEgg()
[]
... 
>>> BoiledEgg[Bar] 
__main__.BoiledEgg[__main__.Bar]
```

However, since [`specification.rst` explicitly states that `Intersection` does not support subtyping](https://github.com/CarliJoy/intersection_examples/blob/667e425949be12849a08f6c094cbb0f867238d09/specification.rst?plain=1#L302), generic type aliases that use `Intersection` should also not support subtyping.

- I think defining "mixin" generic classes might be the role of [`Merged`](https://github.com/CarliJoy/intersection_examples/blob/667e425949be12849a08f6c094cbb0f867238d09/specification.rst?plain=1#L159-L164). We should discuss about that in another issue later.

**Comment by tomasr8** [comment]
Naked `Union` does not support subtyping either so I don't think there's an issue:

```python
class Foo(Union[int, str]): ...
#  TypeError: Cannot subclass typing.Union[int, str]
```
